#!/usr/bin/env zsh
set -o errexit # block commit if there are any issues reported
#───────────────────────────────────────────────────────────────────────────────

echo "Pre-Commit Hook"

echo "(1/3) Biome"
npx biome check --write --error-on-warnings --log-kind="compact" "$(git rev-parse --show-toplevel)"

echo "(2/3) TypeScript"
npx tsc --noEmit --skipLibCheck --strict
echo "Done."

echo "(3/3) Markdownlint"
npx markdownlint --ignore="node_modules" "$(git rev-parse --show-toplevel)"
echo "Done."
echo
