import { appendFileSync } from "node:fs";
import builtins from "builtin-modules";
import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const production = process.argv[2] === "production";

await esbuild
	.build({
		entryPoints: ["src/main.ts"],
		banner: { js: banner },
		outfile: "main.js",
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/view",
			"@lezer/common",
			"@lezer/highlight",
			"@lezer/lr",
			...builtins,
		],
		format: "cjs",
		target: "es2022",
		sourcemap: production ? false : "external",
		minify: production,
		drop: ["debugger"],
		treeShaking: true,
		logLevel: "info",
	})
	.catch(() => process.exit(1));

//──────────────────────────────────────────────────────────────────────────────

// insert correct link to sourcemap file `main.js.map`, as `sourcemap = "inline"`
// does not seem to work
if (!production) {
	const sourcemapFileUrl = import.meta.resolve("./main.js.map");
	const mainJs = import.meta.dirname + "/main.js";
	appendFileSync(mainJs, `\n//# sourceMappingURL=${sourcemapFileUrl}`);
}
