import builtins from "builtin-modules";
import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const production = process.argv[2] === "production";

esbuild
	.build({
		banner: { js: banner },
		entryPoints: ["src/main.ts"],
		bundle: true,
		external: ["obsidian", "electron", ...builtins],
		format: "cjs",
		target: "es2022",
		logLevel: "info",
		sourcemap: production ? false : "inline",
		treeShaking: true,
		minify: production,
		outfile: "main.js",
	})
	.catch(() => process.exit(1));
